name: login_app
description: Aplikasi Login Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.3.6
  get: ^4.6.6
  liquid_swipe: ^3.1.0
  smooth_page_indicator: ^1.1.0
  flutter_otp_text_field: ^1.1.1
  firebase_core: ^2.21.0
  firebase_auth: ^4.13.0
  line_awesome_flutter: ^2.0.0
  cloud_firestore: ^4.13.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_native_splash:
    color: "#f7f6f1"
    color_dark: "#272727"
    image: assets/images/on_boarding_images/flutter_mascot.png
    image_dark: assets/images/on_boarding_images/flutter_mascot.png

    android_12:
      image: assets/images/on_boarding_images/flutter_mascot.png
      icon_background_color: "#f7f6f1"
      image_dark: assets/images/on_boarding_images/flutter_mascot.png
      icon_background_color_dark: "#272727"
    web: false

flutter:

  uses-material-design: true

  assets:
     - assets/logo/
     - assets/images/
     - assets/images/profile/
     - assets/images/dashboard/
     - assets/images/splash_images/
     - assets/images/welcome_images/
     - assets/images/forget_password/
     - assets/images/on_boarding_images/